# GoReleaser configuration for RouteLens
# Documentation: https://goreleaser.com
version: 2

project_name: routelens

before:
  hooks:
    - go mod tidy
    - test -d web/dist

builds:
  - id: routelens
    main: ./cmd/server
    binary: routelens
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows ARM64 is rare, skip it
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - README_CN.md
      - LICENSE
      - deploy/routelens.service
      - deploy/env.example

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Generate .deb and .rpm packages
nfpms:
  - id: routelens-packages
    package_name: routelens
    vendor: RouteLens Contributors
    homepage: https://github.com/yuanweize/RouteLens
    maintainer: RouteLens <noreply@github.com>
    description: |-
      RouteLens - Network Route Monitoring & Visualization Tool
      A self-hosted network monitoring solution with real-time traceroute,
      latency tracking, and geographic visualization.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      # Systemd service file
      - src: deploy/routelens.service
        dst: /lib/systemd/system/routelens.service
        type: config
      # Example environment file
      - src: deploy/env.example
        dst: /etc/routelens/env.example
        type: config
      # Create data directory
      - dst: /var/lib/routelens
        type: dir
        file_info:
          mode: 0755
      # Create config directory
      - dst: /etc/routelens
        type: dir
        file_info:
          mode: 0755
    scripts:
      postinstall: deploy/scripts/postinstall.sh
      preremove: deploy/scripts/preremove.sh
    recommends:
      - mtr
    rpm:
      group: Applications/Internet
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔧 Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "📦 Others"
      order: 999

release:
  github:
    owner: yuanweize
    name: RouteLens
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## RouteLens {{ .Tag }}
    
    A modern, agentless network observability platform.
    
    ### 🚀 Quick Start
    
    **Option 1: Docker (Recommended)**
    ```bash
    docker run -d --name routelens \
      --cap-add NET_RAW --cap-add NET_ADMIN \
      -p 8080:8080 -v $(pwd)/data:/data \
      -e RS_JWT_SECRET=$(openssl rand -hex 32) \
      ghcr.io/yuanweize/routelens:{{ .Tag }}
    ```
    
    **Option 2: Binary + Systemd**
    ```bash
    # Download and extract
    curl -LO https://github.com/yuanweize/RouteLens/releases/download/{{ .Tag }}/routelens_{{ .Version }}_linux_amd64.tar.gz
    tar xzf routelens_{{ .Version }}_linux_amd64.tar.gz
    
    # Install as systemd service
    sudo ./routelens service install --port 8080
    ```
    
    **Option 3: DEB/RPM Package**
    ```bash
    # Debian/Ubuntu
    sudo dpkg -i routelens_{{ .Version }}_linux_amd64.deb
    
    # CentOS/RHEL  
    sudo rpm -i routelens_{{ .Version }}_linux_amd64.rpm
    ```
    
    ### ⚙️ Post-Install
    
    1. Open `http://your-server:8080`
    2. Complete the setup wizard to create admin account
    3. Add monitoring targets in the dashboard
    
    > ⚠️ **Production**: Set `RS_JWT_SECRET` environment variable for persistent sessions.
  footer: |
    ---
    📖 **Documentation**: https://github.com/yuanweize/RouteLens#readme
    🐳 **Docker Hub**: `ghcr.io/yuanweize/routelens:{{ .Tag }}`

# Announce (optional - can be enabled later)
# announce:
#   discord:
#     enabled: false
